### ISSUE TITLE
CommonJS Module Support?

### ISSUE THREAD

**Issue by reintroducing** [estelle/input-masking#2]
First, let me say this looks really nice.  I'm re-evaluating our input masking needs and this looks like a nice alternative.  

I do have two things I'd like to ask about and I'll file separate issues for them. 

The first is support for module loaders.  I personally use Browserify so CJS support would be nice. Maybe AMD support for others that use require would also be a nice touch.  

Thoughts on this?

**Comment by estelle** [comment]
Currently this is framework / tool / module agnostic. I want to make it perfect before I start forking it for individual build environments.

I'll likely switch it to ES6 so I can babel it to a module system of choice fairly easily

**Comment by reintroducing** [comment]
@estelle That's fair. It can be shimmed for the time being. Thank you.
