### ISSUE TITLE
Select all not working

### ISSUE THREAD

**Issue by reintroducing** [estelle/input-masking#3]
The second issue I noticed is support for selecting all text and deleting it.  I have not taken a look at the internals of the script that much yet but there is probably a possibility to check for the key combos to select all text so it can be easily deleted.  Right now that is not possible to do as it deselects right away.

Thanks for listening.

**Comment by estelle** [comment]
Great catch. I will fix that.

**Comment by estelle** [comment]
Resolved: keycode 91 only handled if value changes.

**Comment by reintroducing** [comment]
Not sure if you updated the demo page or not with the new code but it's still not working for me there.

**Comment by estelle** [comment]
I have not yet pushed to GH-Pages. Need to be on my own box to test everything before "pushing to prod".

**Comment by reintroducing** [comment]
Gotcha, makes sense and I figured that something like that was the case but just thought I'd ask.  Thanks again for your work on this.
